<?php 
session_start();
if (isset($SESSION["uname"])) {
 echo "you are login";
 exit();
}
 ?>
<!DOCTYPE html>
<html>
<head>
<title>Demo of session tracking </title>
</head>
<body>
<h1> => session is driven by unique session id.this session id is generated by php and stored on the client side for the lifetime of a session, session can be start by the following syntax. session_start(); </h1>

<h1> => a session end when the user loses the browser or after leaving the site. the server will terminate the session after a predetermined periodof time.. another case when we logout from the account you must destroy the session..</h1>

<h1> => destroy session: </h1>

<form method="post">
<table border="1" align="center" width="400px" height="200px">
<tr>
<td>
username:
</td>
<td><input type="text" name="username"></td>
</tr>

<tr>
<td>
password:
</td>
<td><input type="password" name="pwd"></td>
</tr>
<tr>
<td colspan="2" align="center"><input type="submit" name="submit" value="submit"></td>
</tr>
</table>
</form>
</body>
</html>
<?php

if (isset($_POST['submit'])) {
$_SESSION["uname"]= $_POST['username'];

header('location:userdata.php');
}
?> 